# Lab 8 - Intermediate Python - Data Cleansing with pandas
Objective: Develop your skills in using pandas for data manipulation by focusing on cleaning a dataset with intentional flaws. This task will teach you how to identify and correct common data issues such as missing values, duplicates, and inconsistent entries.

## Import block:

In [1]:
import pandas as pd

## Task 1: Loading and Inspecting the Dataset

### Loading the dataset into a Pandas DataFrame:

In [3]:
df = pd.read_csv("WA_IT-Help-Desk_flaws.csv")

### Inspecting the dataset:

In [5]:
df.head()

,ticket,requestor,RequestorSeniority,ITOwner,FiledAgainst,TicketType,Severity,Priority,daysOpen,Satisfaction
0,1,1929,1 - Junior,50,Systems,Issue,2 - Normal,0 - Unassigned,3.0,1 - Unsatisfied
1,2,1587,2 - Regular,15,Software,Request,1 - Minor,1 - Low,5.0,1 - Unsatisfied
2,3,925,2 - Regular,15,Access/Login,Request,2 - Normal,0 - Unassigned,0.0,0 - Unknown
3,4,413,4 - Management,22,Systems,Request,2 - Normal,0 - Unassigned,20.0,0 - Unknown
4,5,318,1 - Junior,22,Access/Login,Request,2 - Normal,1 - Low,1.0,1 - Unsatisfied

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ticket              100000 non-null  int64
 1   requestor           100000 non-null  int64
 2   RequestorSeniority  100000 non-null  object
 3   ITOwner             100000 non-null  int64
 4   FiledAgainst        100000 non-null  object
 5   TicketType          100000 non-null  object
 6   Severity            100000 non-null  object
 7   Priority            100000 non-null  object
 8   daysOpen            99950 non-null   float64
 9   Satisfaction        100000 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 7.6+ MB

              ticket      requestor        ITOwner      daysOpen
count  100000.000000  100000.000000  100000.000000  99950.000000
mean    50000.500000     999.030670      25.461000      6.842831
std     28867.657797     577.507916      14.447961      7.377611
min         1.000000       1.000000       1.000000      0.000000
25%     25000.750000     499.000000      13.000000      1.000000
50%     50000.500000     999.000000      26.000000      5.000000
75%     75000.250000    1499.000000      38.000000     10.000000
max    100000.000000    2000.000000      50.000000     54.000000

## Task 2: Identifying Data Quality Issues

### Checking for missing values:

In [7]:
df.isnull().sum()

ticket                 0
requestor              0
RequestorSeniority     0
ITOwner                0
FiledAgainst           0
TicketType             0
Severity               0
Priority               0
daysOpen              50
Satisfaction           0
dtype: int64

There is one column with missing values - daysOpen.

### Identify any duplicate rows:

In [44]:
dup = pd.DataFrame(df.duplicated(), columns=['duplicated'])
dup.sum()

duplicated    0
dtype: int64

There are no duplicated rows.

### Spot inconsistencies in categorical data (e.g., different formats or misspellings in categorical entries):

In [24]:
df["RequestorSeniority"].unique()

array(['2 - Normal', '1 - Minor', '3 - Major', '4 - Critical',
       '0 - Unclassified'], dtype=object)

In [25]:
df["TicketType"].unique()

array(['Issue', 'Request'], dtype=object)

In [26]:
df["FiledAgainst"].unique()

array(['Systems', 'Software', 'Access/Login', 'Hardware', 'Hardware!',
       'Acc3ss/Login', 'SyStemsEror', 'softwaRE+'], dtype=object)

In [30]:
df["FiledAgainst"].value_counts()

FiledAgainst
Systems         40033
Access/Login    29920
Software        20067
Hardware         9976
Hardware!           1
Acc3ss/Login        1
SyStemsEror         1
softwaRE+           1
Name: count, dtype: int64

In [27]:
df["Severity"].unique()

array(['2 - Normal', '1 - Minor', '3 - Major', '4 - Critical',
       '0 - Unclassified'], dtype=object)

In [28]:
df["Priority"].unique()

array(['0 - Unassigned', '1 - Low', '3 - High', '2 - Medium'],
      dtype=object)

In [29]:
df["Satisfaction"].unique()

array(['1 - Unsatisfied', '0 - Unknown', '3 - Highly satisfied',
       '2 - Satisfied'], dtype=object)

One categorical column, FiledAgainst, has inconsistent data entries.

## Task 3: Data Cleaning

### Filling missing values

I fill in the missing values with a default value that is representative of the overall distribution - the median. I don't use interpolate, ffill or bfill because the consecutive entries are not necessarily correlated directly with each other. That is, consecutive entries may have different categorical values and the order/index is irrelevant.

In [39]:
median_daysOpen = df["daysOpen"].median(skipna=True)

In [40]:
median_daysOpen

np.float64(5.0)

In [41]:
df = df.fillna(median_daysOpen)

### Correcting inconsistencies

I replace the inconsistent data entries with the most similar standard entries.

In [33]:
df = df.replace("Hardware!", "Hardware")
df = df.replace("Acc3ss/Login", "Access/Login")
df = df.replace("SyStemsEror", "Systems")
df = df.replace("softwaRE+", "Software")

## Task 4: Data Validation

In [48]:
df.head()

,ticket,requestor,RequestorSeniority,ITOwner,FiledAgainst,TicketType,Severity,Priority,daysOpen,Satisfaction
0,1,1929,1 - Junior,50,Systems,Issue,2 - Normal,0 - Unassigned,3.0,1 - Unsatisfied
1,2,1587,2 - Regular,15,Software,Request,1 - Minor,1 - Low,5.0,1 - Unsatisfied
2,3,925,2 - Regular,15,Access/Login,Request,2 - Normal,0 - Unassigned,0.0,0 - Unknown
3,4,413,4 - Management,22,Systems,Request,2 - Normal,0 - Unassigned,20.0,0 - Unknown
4,5,318,1 - Junior,22,Access/Login,Request,2 - Normal,1 - Low,1.0,1 - Unsatisfied

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ticket              100000 non-null  int64
 1   requestor           100000 non-null  int64
 2   RequestorSeniority  100000 non-null  object
 3   ITOwner             100000 non-null  int64
 4   FiledAgainst        100000 non-null  object
 5   TicketType          100000 non-null  object
 6   Severity            100000 non-null  object
 7   Priority            100000 non-null  object
 8   daysOpen            100000 non-null  float64
 9   Satisfaction        100000 non-null  object
dtypes: float64(1), int64(3), object(6)
memory usage: 7.6+ MB

In [45]:
df.isnull().sum()

ticket                0
requestor             0
RequestorSeniority    0
ITOwner               0
FiledAgainst          0
TicketType            0
Severity              0
Priority              0
daysOpen              0
Satisfaction          0
dtype: int64

In [46]:
df["FiledAgainst"].unique()

array(['Systems', 'Software', 'Access/Login', 'Hardware'], dtype=object)

## AI Usage

## References
https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.duplicated.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html